version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - DB_USERNAME="lazuli"
      - DB_PASSWORD="x1RWo6cqFtHiaAHce5HB"
      - DB_HOST=mongo
      - DB_PORT=27017

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
  mongo:
    container_name: mongo
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lazuli
      - MONGO_INITDB_ROOT_PASSWORD=x1RWo6cqFtHiaAHce5HB
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
